### ISSUE TITLE
IMPORTANT

### ISSUE THREAD

**Issue by BIGFATRYAN** [Joshua-Usi/osw#20]
The bug I want to report is that immense lag when I play the game (it might just be that I'm on a Chromebook) and I would like you to remove the mouse acceleration when playing the game because it is really hard to play with that.

**Comment by Joshua-Usi** [comment]
In order to turn off mouse acceleration, Turn ON "Use tablet raw position"

![image](https://user-images.githubusercontent.com/49742616/148494193-4eb4f16b-4181-40b4-b5af-f3200f0ebc11.png)

This uses the raw mouse speed set by your computer, instead of the customisable sensitivity options

Lag is a huge problem with the canvas API and is generally unfixable,  A move to webgl will fix it but requires an entire rewrite for the renderer
